name: weekly_tasks
description: Tiny project for internal use - to set and collect weekly tasks for private purposes.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  bloc_test: ^9.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_auth: ^4.2.7
  firebase_core: ^2.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localization: ^0.1.10
  flutter_tts: ^3.6.3
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^6.0.4
  hydrated_bloc: ^9.1.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.12
  uuid: ^3.0.6
  

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.3
  json_serializable: ^6.3.1
  mocktail: ^0.3.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
